## Numpy array and basics 
learn about Numpy with chai aur code 

In [1]:
import numpy as np

## creating array from list 

In [2]:
arr_1d=np.array([1,2,3,4,5])
print("1D Array:", arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array: \n",arr_2d)


1D Array: [1 2 3 4 5]
2D Array: 
 [[1 2 3]
 [4 5 6]]


## Python list vs Numpy array


In [3]:
py_list=[1,2,3]
print("python list multiplication :", py_list * 2)

np_arr = np.array([4,5,6])    # element wise multiplication
print("Python arry multiplication :", np_arr * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nlist operation time:",time.time()-start)

start = time.time()
np_array= np.arange(100000) *2
print("Numpy operation time:",time.time()-start)


python list multiplication : [1, 2, 3, 1, 2, 3]
Python arry multiplication : [ 8 10 12]

list operation time: 0.054341793060302734
Numpy operation time: 0.000370025634765625


## creating array from scratch

In [4]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)


full = np.full((2,2),7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n",random)


sequence  = np.arange(0,10,2)
print("sequence array: \n", sequence)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.08004252 0.60808688 0.68178452]
 [0.69157923 0.19525936 0.6597866 ]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [5]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape",arr.shape)
print("dimension ",arr.ndim)
print("Size ",arr.size)
print("Data type ",arr.dtype)


Shape (2, 3)
dimension  2
Size  6
Data type  int64


## Array reshaping

In [7]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3,4))       #converts this array into (3,4)matrix
print("Reshaped array: \n",reshaped)

flattened = reshaped.flatten()      #flatten the matrix array 
print("Flatten Array: \n", flattened)

raveled = reshaped.ravel()          #ravel (returns view, instead of copy)
print("Raveled Array: \n",raveled)

transpose = reshaped.T            #transposes the array 
print("Transposed Array: \n",transpose)



Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
