## Numpy Array operations

In [1]:
import numpy as np

## Indexing and slicing of 1D array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic indexing:",arr[2:7])
print("With step:", arr[1:8:2])
print("Negative indexing:",arr[-3])

Basic indexing: [3 4 5 6 7]
With step: [2 4 6 8]
Negative indexing: 8


## Indexing and slicing of 2D array

In [3]:
arr_2d= np.array([[1,2,3],      #0th row [element sekuence = (0th,1st,2nd)]
                  [4,5,6],      #1st row
                  [7,8,9]])     #2nd row 
print("specific element:",arr_2d[1,2])       #means we are getting 2nd element of 1st row
print("Entire row:",arr_2d[1])            #getting the whole 1st row
print("Entire column:",arr_2d[:, 2])        #getting 2nd element of each row i.e. 2nd column 

specific element: 6
Entire row: [4 5 6]
Entire column: [3 6 9]


# Sorting

In [4]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted array:",np.sort(unsorted))


arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array (column wise): \n",np.sort(arr_2d_unsorted, axis= 0))
print("Sorted 2d array (row wise): \n",np.sort(arr_2d_unsorted, axis= 1))

Sorted array: [1 1 2 3 4 5 6 9]
Sorted 2d array (column wise): 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array (row wise): 
 [[1 3]
 [1 2]
 [2 3]]


## Filter 

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers= numbers[numbers % 2 ==0]
print("Even Numbers",even_numbers)

Even Numbers [ 2  4  6  8 10]


## Filter with Mask

In [6]:
mask = numbers>5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [7]:
indices = [0,2,4]
print(numbers[indices])

where_result= np.where(numbers>5)
print(where_result)
print("NP where:",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [8]:
condition_array= np.where(numbers>5,"True","False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding and Removing Data

In [9]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## Array compatibility

In [10]:
a= np.array([1,2,3])
b=np.array([4,5,6])
c= np.array([7,8,9])

print("Compatibility shapes: ",a.shape == b.shape)

Compatibility shapes:  True


## Vstack and Hstack

In [11]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))
print("with new row:\n",with_new_row)

new_col= np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new column:\n",with_new_col)

with new row:
 [[1 2]
 [3 4]
 [5 6]]
with new column:
 [[1 2 7]
 [3 4 8]]


# Deletion

In [12]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion: \n",arr)


Array after deletion: 
 [1 2 3 4 5]
